# Change these first
owner: jparkrr # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
skipDeleteIssues: true
assignees: # Users to assign downtime issues (optional)
  - jparkrr

sites:
  - name: Availability April
    url: https://www.recreation.gov/api/permititinerary/4675337/division/4675337032/availability/month?month=4&year=2025
    __dangerous__body_down: "\":true,\"2025"
  - name: Availability May
    url: https://www.recreation.gov/api/permititinerary/4675337/division/4675337032/availability/month?month=5&year=2025
    __dangerous__body_down: "\":true,\"2025"
  - name: Availability June
    url: https://www.recreation.gov/api/permititinerary/4675337/division/4675337032/availability/month?month=6&year=2025
    __dangerous__body_down: "\":true,\"2025"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
